swagger: '2.0'
info:
  description: Drone navigation system interface
  version: 1.0.0
  title: DNS API
basePath: /api/v1
tags:
  - name: DNS
    description: Drone navigation system interface contacted via this swagger
    externalDocs:
      description: Find out more
      url: 
paths:
  /:
    post:
      summary: Retrieve drone location
      description: Retrieve drone location via API call
      operationId: GetLocationRequest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: GetLocationRequest
          required: true
          schema:
            $ref: '#/definitions/GetLocationRequest'
      responses:
        '200':
          description: 'Location retrieved'
        '400':
          description: 'Invalid input, object invalid'
        '500':
          description: 'Service failure'
definitions:
  GetLocationResponse:
    type: object
    properties:
      loc:
        type: float64
        example: 434.00
  GetLocationRequest:
    type: object
    properties:
      x:
        type: float64
        example: 34.0
      y:
        type: float64
        example: 767.00
      z:
        type: float64
        example: 45.0
      vel:
        type: float64
        example: 123.0